lib/langtool_pro_web/router.ex
defmodule LangtoolProWeb.Router do
  use LangtoolProWeb, :router

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
    get "/preview_emails/:name/:type", LangtoolProWeb.PreviewEmailController, :show
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LangtoolProWeb do
    pipe_through :browser

    get "/", PageController, :index, as: :welcome
    # signup routes
    get "/signup", RegistrationController, :new
    resources "/registration", RegistrationController, only: [:create]
    get "/registration/complete", RegistrationController, :complete, as: :complete
    get "/registration/confirm", RegistrationController, :confirm, as: :confirm
    # sessions resources
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
    # settings
    resources "/settings", SettingsController, only: [:index]
    resources "/translation_keys", TranslationKeysController, except: [:show]
    # tasks
    resources "/tasks", TasksController, except: [:show, :edit, :update]
  end

  # api resources
  scope "/api/v1", LangtoolProWeb.Api.V1, as: :api do
    pipe_through :api

    resources "/users", UsersController, only: [:create]
    resources "/user_tokens", UserTokensController, only: [:create]
    resources "/translation_keys", TranslationKeysController, only: [:index, :create, :update, :delete]
    post "/tasks/detection", TasksController, :detection, as: :detection
  end
end

lib/langtool_pro_web/views/shared_view.ex
defmodule LangtoolProWeb.SharedView do
  use LangtoolProWeb, :view
end

lib/langtool_pro_web/templates/shared/alerts.html.eex
<div class="alerts">
  <div class="container">
    <%= Enum.map(get_flash(@conn), fn {key, value} -> %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end) %>
  </div>
</div>

lib/langtool_pro_web/templates/shared/footer.html.eex
<footer>
  <div class="container flex">
    <div>
      <p>Currently v0.1.3.</p>
    </div>
    <div>
      <img src="/images/junglecoders.png" />
      <p>by Bogdanov Anton</p>
    </div>
  </div>
</footer>

lib/langtool_pro_web/templates/shared/navigation.html.eex
<nav>
  <div class="container flex">
    <%= link "LangTool", to: welcome_path(@conn, :index), class: "navbar-brand decoration_none" %>
    <div class="navbar-right">
      <%= if signed_in?(@conn) do %>
        <div id="user_menu">
          <p class="toggler" @click.prevent="openMenu" v-click-outside="hideMenu">
            Profile
          </p>
          <div class="menu flex column" v-show="opened">
            <%= link "Tasks", to: tasks_path(@conn, :index), class: "decoration_none" %>
            <%= link "Settings", to: settings_path(@conn, :index), class: "decoration_none" %>
            <%= link "SignOut", to: session_path(@conn, :delete), method: :delete, class: "decoration_none" %>
          </div>
        </div>
      <% else %>
        <%= link "SignIn", to: session_path(@conn, :new), class: "decoration_none" %>
        <%= link "SignUp", to: registration_path(@conn, :new), class: "decoration_none" %>
      <% end %>
    </div>
  </div>
</nav>