lib/langtool_pro_web/router.ex
defmodule LangtoolProWeb.Router do
  use LangtoolProWeb, :router

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
    get "/preview_emails/:name/:type", LangtoolProWeb.PreviewEmailController, :show
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LangtoolProWeb do
    pipe_through :browser

    get "/", PageController, :index, as: :welcome
    # signup routes
    get "/signup", RegistrationController, :new
    resources "/registration", RegistrationController, only: [:create]
    get "/registration/complete", RegistrationController, :complete, as: :complete
    get "/registration/confirm", RegistrationController, :confirm, as: :confirm
    # sessions resources
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create
    delete "/signout", SessionController, :delete
    # settings
    resources "/settings", SettingsController, only: [:index]
    resources "/translation_keys", TranslationKeysController, except: [:show]
    # tasks
    resources "/tasks", TasksController, except: [:show, :edit, :update]
  end

  # api resources
  scope "/api/v1", LangtoolProWeb.Api.V1, as: :api do
    pipe_through :api

    resources "/users", UsersController, only: [:create]
    resources "/user_tokens", UserTokensController, only: [:create]
    resources "/translation_keys", TranslationKeysController, only: [:index, :create, :update, :delete]
    post "/tasks/detection", TasksController, :detection, as: :detection
  end
end

lib/langtool_pro/tasks.ex
defmodule LangtoolPro.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias LangtoolPro.{Repo, Tasks.Task, Services}

  @doc """
  Get tasks list for user

  ## Examples

      iex> get_tasks_for_user(user)

  """
  def get_tasks_for_user(user_id) when is_integer(user_id) do
    query =
      from task in Task,
      where: task.user_id == ^user_id,
      order_by: [desc: task.id]

    Repo.all(query)
  end

  @doc """
  Gets a single task

  ## Examples

      iex> get_task(123)
      %Task{}

      iex> get_task(123)
      nil

  """
  def get_task(id) when is_integer(id), do: Repo.get(Task, id)

  @doc """

  Gets a service name for task

  ## Examples

      iex> get_service_for_task(123)
      %Service{}

      iex> get_service_for_task(123)
      nil

  """
  def get_service_for_task(id) when is_integer(id) do
    case get_task(id) do
      nil -> nil
      task ->
        Repo.preload(task, :translation_key).translation_key.service_id
        |> Services.get_service()
    end
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_translation_key(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task), do: Task.changeset(task, %{})

  @doc """
  Creates a task

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs) when is_map(attrs) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates status of the task

  ## Examples

      iex> update_task_status(task, status)
      {:ok, %Task{}}

  """
  def update_task_status(%Task{} = task, status) when is_binary(status) do
    task
    |> Task.status_changeset(%{status: status})
    |> Repo.update()
  end

  @doc """
  Updates a task

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) when is_map(attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Attaches file to task

  ## Examples

      iex> attach_file(task, %{field: value})

  """
  def attach_file(%Task{} = task, attrs) when is_map(attrs) do
    task
    |> Task.file_changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

  """
  def delete_task(%Task{} = task), do: Repo.delete(task)

  @doc """
  Detects locale for file

  ## Examples

      iex> detect_locale(filename, path)
      {:ok, %{code: "en"}}

      iex> detect_locale(filename, path)
      {:error, ""}

  """
  def detect_locale(filename, path, framework) when is_binary(filename) and is_binary(path) and is_binary(framework) do
    extension =
      filename
      |> String.split(".")
      |> Enum.at(-1)
    do_detect_locale(path, extension, framework, filename)
  end

  defp do_detect_locale(_, "json", "laravel", filename), do: I18nParser.detect("", "json", %{data_with_locale: false, filename: filename})
  defp do_detect_locale(path, "json", "react_js", _), do: I18nParser.detect(path, "json", %{data_with_locale: true})
  defp do_detect_locale(path, extension, _, _), do: I18nParser.detect(path, extension)

  @doc """
  Attaches result file to task

  ## Examples

      iex> save_result_file("content", task)

  """
  def save_result_file(result_file_content, %Task{} = task) when is_binary(result_file_content) do
    result_file_name = task.to <> ".yml"
    # create temp folder
    temp_folder = File.cwd! |> Path.join(LangtoolPro.File.temp_storage_dir(:original, {:abc, task}))
    File.mkdir(temp_folder)
    # create temp file
    temp_file_path = temp_folder <> "/#{result_file_name}"
    File.write(temp_file_path, result_file_content)
    # attach temp file as result to task
    save_result = attach_result_file(task, %{result_file: %Plug.Upload{filename: result_file_name, path: temp_file_path}})
    # delete temp file
    File.rm(temp_file_path)
    save_result
  end

  defp attach_result_file(%Task{} = task, %{} = attrs) do
    task
    |> Task.result_file_changeset(attrs)
    |> Repo.update()
  end
end

lib/langtool_pro/tasks/task.ex
defmodule LangtoolPro.Tasks.Task do
  use Ecto.Schema
  use Arc.Ecto.Schema
  import Ecto.Changeset
  alias LangtoolPro.{Users.User, Tasks.Task, TranslationKeys, TranslationKeys.TranslationKey, Helpers}

  schema "tasks" do
    field :file, LangtoolPro.File.Type
    field :result_file, LangtoolPro.ResultFile.Type
    field :from, :string
    field :to, :string
    field :status, :string
    field :uid, :string

    belongs_to :user, User
    belongs_to :translation_key, TranslationKey

    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:user_id, :translation_key_id, :from, :to, :status])
    |> assoc_constraint(:user)
    |> validate_translation_key()
    |> validate_required([:from, :to, :status])
    |> validate_inclusion(:status, ["created", "active", "failed", "completed"])
    |> validate_length(:from, min: 2)
    |> validate_length(:to, min: 2)
    |> put_change(:uid, Helpers.random_string(12))
  end

  @doc false
  def file_changeset(%Task{} = task, attrs) do
    task
    |> cast_attachments(attrs, [:file], [])
    |> validate_required([:file])
  end

  @doc false
  def result_file_changeset(%Task{} = task, attrs) do
    task
    |> cast_attachments(attrs, [:result_file], [])
    |> validate_required([:result_file])
  end

  @doc false
  def status_changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:status])
    |> validate_inclusion(:status, ["created", "active", "failed", "completed"])
  end

  defp validate_translation_key(changeset) do
    validate_change(changeset, :translation_key_id, fn _, translation_key_id ->
      case TranslationKeys.get_translation_key(translation_key_id) do
        nil ->
          [translation_key: "is not found"]
        translation_key ->
          case translation_key.user_id == get_field(changeset, :user_id) do
            true -> []
            _ -> [translation_key: "does not belong to user"]
          end
      end
    end)
  end
end

lib/langtool_pro_web/controllers/api/v1/tasks_controller.ex
defmodule LangtoolProWeb.Api.V1.TasksController do
  use LangtoolProWeb, :controller_api
  alias LangtoolPro.{Tasks}

  def detection(conn, %{"file" => %Plug.Upload{filename: filename, path: path}, "framework" => framework}) do
    case Tasks.detect_locale(filename, path, framework) do
      {:ok, message} ->
        conn
        |> put_status(200)
        |> render("detection.json", message: message)
      {:error, message} ->
        conn
        |> put_status(200)
        |> render("detection.json", message: message)
      _ ->
        render_error(conn, 400, "Unknown error")
    end
  end
end

lib/langtool_pro_web/controllers/tasks_controller.ex
defmodule LangtoolProWeb.TasksController do
  use LangtoolProWeb, :controller
  alias LangtoolPro.{Tasks, Tasks.Task}

  plug :check_auth when action in [:index, :new, :create, :delete]
  plug :check_confirmation when action in [:index, :new, :create, :delete]
  plug :find_task when action in [:delete]
  plug :check_authorize when action in [:delete]

  def index(conn, _) do
    conn
    |> assign(:tasks, Tasks.get_tasks_for_user(conn.assigns.current_user.id))
    |> render("index.html")
  end

  def new(conn, _) do
    conn
    |> assign(:changeset, Tasks.change_task(%Task{}))
    |> render("new.html")
  end

  def create(conn, %{"task" => task_params, "framework" => framework}) do
    task_params
    |> Map.merge(%{"user_id" => conn.assigns.current_user.id})
    |> Tasks.create_task()
    |> case do
      {:ok, task} ->
        case Tasks.attach_file(task, task_params) do
          {:ok, task} ->
            LangtoolPro.Supervisors.TaskHandle.call(task, framework)
            conn
            |> put_flash(:success, "Task created successfully.")
            |> redirect(to: tasks_path(conn, :index))
          _ ->
            conn
            |> put_flash(:danger, "File attaching error")
            |> render("new.html")
        end
      {:error, _} ->
        conn
        |> put_flash(:danger, "Task is not created")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    Tasks.delete_task(conn.assigns.task)
    conn
    |> put_flash(:success, "Task deleted successfully.")
    |> redirect(to: tasks_path(conn, :index))
  end

  defp find_task(conn, _) do
    task = conn.params["id"] |> String.to_integer() |> Tasks.get_task()
    case task do
      nil ->
        conn
        |> put_flash(:danger, "Task is not found")
        |> redirect(to: tasks_path(conn, :index))
        |> halt()
      _ ->
        assign(conn, :task, task)
    end
  end

  defp check_authorize(conn, _) do
    authorize(conn, :task, :"#{conn.private.phoenix_action}?", conn.assigns.task)
  end
end

lib/langtool_pro_web/views/tasks_view.ex
defmodule LangtoolProWeb.TasksView do
  use LangtoolProWeb, :view
  alias LangtoolPro.TranslationKeys

  def translation_keys_of_user(user_id) do
    TranslationKeys.get_translation_keys_for_user(user_id)
  end
end

lib/langtool_pro_web/templates/tasks/index.html.eex
<div id="tasks" class="container">
  <div class="section">
    <div class="head">
      Tasks
    </div>
    <%= link "Start new task", to: tasks_path(@conn, :new), class: "btn btn-primary btn-small decoration_none", id: "new_key_button" %>
    <div class="tasks">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">File name</th>
            <th scope="col">Direction</th>
            <th scope="col">Status</th>
            <th scope="col">Result</th>
          </tr>
        </thead>
        <tbody>
          <%= for task <- @tasks do %>
            <tr>
              <th scope="col"><%= task.id %></th>
              <td scope="col"><%= task.file.file_name %></td>
              <td scope="col"><%= "#{task.from}-#{task.to}" %></td>
              <td scope="col" class="status"><%= task.status %></td>
              <td scope="col" class="result">
                <%= if task.status == "completed" do %>
                  <a class="btn btn-primary btn-mini decoration_none" download href="<%= LangtoolPro.ResultFile.url({task.result_file,task}, signed: true) %>">Download</a>
                <% end %>
                <%= if task.status != "active" do %>
                  <%= link "Delete", to: tasks_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-mini decoration_none" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

lib/langtool_pro_web/templates/tasks/new.html.eex
<div id="tasks" class="container flex">
  <div class="left">
    <div id="new_task_description">
      <p class="header">New task creation process</p>
      <ul>
        <li>Select framework to define type of localization file</li>
        <li>Then you will need to select file<p class="caption">Original language of this file will be automatically detected</p></li>
        <li>And choose translation key<p class="caption">If you don't have translation keys then you need to add it at <%= link "translation keys page", to: translation_keys_path(@conn, :index), class: "decoration_none" %></p></li>
        <li>Last, you will need to choose target language of translation<p class="caption">Right now you can translate only between english and other language</p></li>
        <li>Task will proceed automatically and you will see result of translation at <%= link "tasks page", to: tasks_path(@conn, :index), class: "decoration_none" %></li>
      </ul>
    </div>
  </div>
  <div class="right">
    <div class="section">
      <div class="head">
        New task
      </div>
      <form id="new_task">
        <input type="hidden" id="_csrf_token" value="<%= get_csrf_token() %>">
        <div class="form-group" :class="{ current: framework === '' }">
          <label for="select_framework">Select framework</label>
          <select class="form-control" id="select_framework" v-model="framework">
            <option disabled="" selected="" value="">Select your option</option>
            <option value="ruby_on_rails">Ruby on Rails</option>
            <option value="react_js">React JS</option>
            <option value="laravel">Laravel</option>
          </select>
        </div>
        <div class="form-group" :class="{ disabled: framework === '', current: framework !== '' && fileName === null || fileError }">
          <label for="localization_file" class="file_uploader" :class="{ error: fileError }">{{ error || fileName || "Upload the file for localization" }}</label>
          <input type="file" class="form-control-file" id="localization_file" :accept="extension" @change="uploadFile($event)" />
        </div>
        <div class="form-group" :class="{ disabled: fileName === null || fileError, current: fileName !== null && !fileError && translationKey === null }">
          <label for="select_translation_key">Select translation key</label>
          <select class="form-control" id="select_translation_key" v-model="translationKey">
            <option disabled="" selected="" value="">Select your option</option>
            <%= for translation_key <- translation_keys_of_user(@current_user.id) do %>
              <option value="<%= translation_key.id %>"><%= translation_key.name %></option>
            <% end %>
          </select>
        </div>
        <div class="row">
          <div class="form-group disabled">
            <label for="original_language">Original language</label>
            <input type="text" id="original_language" :value="originalLanguage" />
          </div>
          <div class="form-group" :class="{ disabled: translationKey === null, current: translationKey !== null && to === '' }">
            <label for="translation_language">Language of translation</label>
            <select class="form-control" id="translation_language" v-model="to">
              <option disabled="" selected="" value="">Select your option</option>
              <option value="da" :disabled="from === 'da' || from !== 'en'">Danish</option>
              <option value="de" :disabled="from === 'de' || from !== 'en'">Deutsch</option>
              <option value="en" :disabled="from === 'en'">English</option>
              <option value="fr" :disabled="from === 'fr' || from !== 'en'">French</option>
              <option value="ru" :disabled="from === 'ru' || from !== 'en'">Russian</option>
              <option value="es" :disabled="from === 'es' || from !== 'en'">Spanish</option>
            </select>
          </div>
        </div>
        <div class="row">
          <button class="btn btn-primary btn-small" type="button" :class="{ disabled: from === '' || to === '' }" @click.prevent="createTask()">
            Create task
          </button>
        </div>
      </form>
    </div>
  </div>
</div>